---
build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.18
  armhf: ghcr.io/home-assistant/armhf-base:3.18
  armv7: ghcr.io/home-assistant/armv7-base:3.18
codenotary:
  signer: notary@home-assistant.io
  base_image: notary@home-assistant.io
args:
  SMARTHUB_VERSION: 0.9.5