name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: "0.9.5"
slug: "smart_hub"
init: true
arch:
  - aarch64
  - armhf
  - armv7
ports:
  7777/udp: 7777
  7780/tcp: 7780
host_network: true
full_access: true
devicetree: true
hassio_role: "admin"
"hassio_api": true
"homeassistant_api": true
"image": "ghcr.io/dneprojects/smart_hub-{arch}"