---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: edge
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
hassio_api: true
homeassistant_api: true
host_network: true
uart: true
gpio: true
devices: ["dev/serial0"]
devicetree: true
hassio_role: manager
full_access: false
image: "ghcr.io/dneprojects/smart_hub/{arch}"
webui: http://[HOST]:[PORT:7780]/
