---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: 0.9.6
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
hassio_api: true
hassio_role: manager
homeassistant_api: true
host_network: true
uart: true
devicetree: true
image: "ghcr.io/dneprojects/smart_hub/{arch}"
init: false
host_pid: true
