---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: dev
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
host_network: true
full_access: true
devicetree: true
hassio_role: "admin"
"hassio_api": true
"homeassistant_api": true
"image": "ghcr.io/dneprojects/smart_hub/{arch}"
