---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: 1.1.6
slug: "smart_hub"
arch:
  - aarch64
startup: services
init: false
ports:
  7777/udp: 7777
  7780/tcp: 7780
host_network: true
uart: true
devicetree: true
devices: ["dev/serial0"]
map: [addon_config:rw]
full_access: false
hassio_role: default
hassio_api: true
homeassistant_api: false
environment: {'SUPERVISOR_TOKEN': '', 'TEST_KEY': "test"}
image: "ghcr.io/dneprojects/smart_hub/{arch}"
webui: http://[HOST]:[PORT:7780]/
