---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: 1.1.6
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
startup: services
init: false
full_access: false
hassio_api: true
hassio_role: default
homeassistant_api: false
host_network: true
map: [addon_config:rw]
devices: ["dev/serial0"]
uart: true
devicetree: true
ingress: true
image: "ghcr.io/dneprojects/smart_hub/{arch}"
webui: http://[HOST]:[PORT:7780]/
