---
name: "Smart Hub"
description: "Habitron Smart Hub as Home Assistant Add-on"
version: 0.9.8
slug: "smart_hub"
arch:
  - aarch64
ports:
  7777/udp: 7777
  7780/tcp: 7780
hassio_api: true
hassio_role: admin
homeassistant_api: true
host_network: true
uart: true
gpio: true
devices: ["dev/serial0"]
devicetree: true
image: "ghcr.io/dneprojects/smart_hub/{arch}"
init: false
host_pid: false
webui: http://[HOST]:[PORT:7780]/
